### ISSUE TITLE
Breakout is broke

### ISSUE THREAD

**Issue by Functional-Self** [RVAGameJams/learn2love#32]
I'm stuck on version 2 of the Breakout game and the problem seems to be in the original source code itself, not just my attempt to retype it. I've done a few Google searches and can't find anyone having a problem close enough to mine to translate.

**Error**

entities/paddle.lua:14: attempt to index local 'self' (a nil value)

Traceback

entities/paddle.lua:14: in function 'draw'
main.lua:20: in function 'draw'
[C]: in function 'xpcall'

**The File**

-- entities/paddle.lua

local world = require('world')

return function(pos_x, pos_y)
  local entity = {}
  entity.body = love.physics.newBody(world, pos_x, pos_y, 'static')
  entity.shape = love.physics.newRectangleShape(180, 20)
  entity.fixture = love.physics.newFixture(entity.body, entity.shape)
  entity.fixture:setUserData(entity)

  entity.draw = function(self)
    love.graphics.polygon('line', self.body:getWorldPoints(self.shape:getPoints()))
  end

  return entity
end

By the way thank you for this guide, it's been very readable and helpful except for moments like this, where I presume Lua got updated and in some way rendered the original document outdated.

**Comment by jaythomas** [comment]
Thanks for the feedback!

Running that version of the code I am not able to reproduce the problem, but looking at your error message:

> entities/paddle.lua:14: in function 'draw'
> main.lua:20: in function 'draw'
> [C]: in function 'xpcall'

the problem seems to originate from `main.lua` line 20 in the "draw" (love.draw) function.

Have a look at [this line](https://github.com/RVAGameJams/learn2love/blob/a877ee45f3c8a14788b9423730afceecc4e03482/code/breakout-2/main.lua#L20) and verify your code matches this. One gotcha with Lua is calling `entity.draw()` versus calling `entity:draw()`. If you call the first one the 'self' variable inside the `entity.draw` function will be a nil value. This is explained a little better near the end of the Breakout Part 2 article.

If this isn't the issue would you mind sharing your main.lua file? Or even better, push up your test code to a git repo.

**Comment by Functional-Self** [comment]
Oh! Yeah, I was focusing on the paddle bit, not the main file. Yes, I had a period instead of a colon, here and in the ball file it turns out. Thank you for the prompt response, that fixed the problem.
